# if --version is specified during CLI run 
# the CLI will try to use the same docker-compose git ref and docker tags
# --version v0.x.y will use the v0.x.y tag for all images and the compose file from the v0.x.y git tag
# quickstart_version_map maps broken releases to fixed ones
# key is the broken release
# .composefile_git_ref: the git ref of the compose file to use
# .docker_tag: the docker tag to use
# if no version is specified the default key will be used
#
# in case of --version stable the latest released version will be used (by querying the github api)
# the mapping for stable is not required, but can be used to override the latest release
quickstart_version_map:
  # default key is mandatory and is used if no version is specified
  # in case of a broken release or broken master branch 
  # specify a working version here
  default:
    composefile_git_ref: master
    docker_tag: head
  # v0.9.6 images contain security vulnerabilities 
  v0.9.6: 
    composefile_git_ref: v0.9.6.1
    docker_tag: v0.9.6.1
  # if stable is not defined the latest released version will be used
  # stable: 
  #   composefile_git_ref: master
  #   docker_tag: head