---
version: '3.5'
services:
  datahub-frontend:
    image: keremsahin/datahub-frontend:latest
    hostname: datahub-frontend
    container_name: datahub-frontend
    ports:
      - "9001:9001"
    environment:
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080

networks:
  default:
    name: datahub_network