---
version: '3.5'
services:
  datahub-gms:
    image: keremsahin/datahub-gms:latest
    hostname: datahub-gms
    container_name: datahub-gms
    ports:
      - "8080:8080"
    environment:
      - ebean.datasourceUsername=datahub
      - ebean.datasourcePassword=datahub
      - ebean.datasourceUrl=jdbc:mysql://mysql:3306/datahub
      - ebean.datasourceDriver=com.mysql.jdbc.Driver
      - kafka.bootstrapServers=broker:29092
      - kafka.schemaRegistryUrl=http://schema-registry:8081
      - elasticsearch.hosts=elasticsearch
      - elasticsearch.port=9200
      - DATAHUB_MYSQL_HOST=mysql:3306
      - DATAHUB_KAFKA_BROKER_HOST=broker:29092
      - DATAHUB_ELASTICSEARCH_HOST=elasticsearch:9200

networks:
  default:
    name: datahub_network