name: datahub-ingest docker
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.github/workflows/docker-ingest.yml'
    paths_ignore:
      - '**.md'
      - '**.env'
  release:
    types: [published, edited]

jobs:
  push_to_registries:
    name: Push Docker image to repo
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
            dockerfile: ./docker/Dockerfile
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            repository: acryldata/designpartners
            tag_with_ref: true
