apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datahub-gms.fullname" . }}-secret
  labels:
    {{- include "datahub-gms.labels" . | nindent 4 }}
type: Opaque
stringData:
  datahub.gms.secret: "{{ .Values.global.datahub.gms.secret }}"
  ebean.datasource.username: "{{ .Values.global.sql.datasource.username }}"
  ebean.datasource.password: "{{ .Values.global.sql.datasource.password }}"
  neo4j.username: "{{ .Values.global.neo4j.username }}"
  neo4j.password: "{{ .Values.global.neo4j.password }}"