apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-gms-secret" .Release.Name }}
  labels:
    {{- include "datahub-gms.labels" . | nindent 4 }}
type: Opaque
data:
  datahub.gms.secret: {{ randAlphaNum 10 | b64enc | quote }}