# Introduces datahub-frontend-ember service to serve the Ember UI on localhost:9001/
---
version: '3.8'
services:
  datahub-frontend-ember:
    build:
      context: ../
      dockerfile: docker/datahub-frontend/Dockerfile
      args:
        SERVER_PORT: 9001
        ENABLE_EMBER: "true"
    image: linkedin/datahub-frontend:${DATAHUB_VERSION:-latest}
    env_file: datahub-frontend/env/docker.env
    hostname: datahub-frontend
    container_name: datahub-frontend
    ports:
      - "9001:9001"
    depends_on:
      - datahub-gms
