# Service definitions for Kafka Setup container.
version: '3.8'
services:

  # This "container" is a workaround to pre-create topics
  kafka-setup:
    build:
      context: kafka-setup
    image: ${DATAHUB_KAFKA_SETUP_IMAGE:-linkedin/datahub-kafka-setup}:${DATAHUB_VERSION:-head}
    env_file: kafka-setup/env/docker.env
    hostname: kafka-setup
    container_name: kafka-setup
    depends_on:
      - broker
      - schema-registry