---
version: '3.5'
services:
  ingestion:
    image: datahub-ingestion
    build:
      context: ../../
      dockerfile: docker/ingestion/Dockerfile
    hostname: ingestion
    container_name: ingestion
    environment:
      - KAFKA_BOOTSTRAP_SERVER=broker:29092
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081

networks:
  default:
    name: datahub_network