apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datahub-frontend.fullname" . }}-secret
  labels:
    {{- include "datahub-frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  datahub.gms.secret: "{{ .Values.global.datahub.gms.secret }}"