apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-mce-consumer-deployment
  labels:
    app: datahub-mce-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-mce-consumer
  template:
    metadata:
      labels:
        app: datahub-mce-consumer
    spec:
      containers:
        - name: datahub-mce-consumer
          image: linkedin/datahub-mce-consumer:latest
          command: ["/bin/sh", "-c" ,"./mce-consumer-job/bin/mce-consumer-job"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: kafka.bootstrap.server
            - name: KAFKA_SCHEMAREGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: kafka.schemaregistry.url
            - name: DATAHUB_GMS_HOST
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: datahub.gms.host
            - name: DATAHUB_GMS_PORT
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: datahub.gms.port