apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-gms-deployment
  labels:
    app: datahub-gms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-gms
  template:
    metadata:
      labels:
        app: datahub-gms
    spec:
      containers:
        - name: datahub-gms
          image: linkedin/datahub-gms:latest
          ports:
          - containerPort: 8080
          command: ["/bin/sh", "-c" ,"java -jar jetty-runner-9.4.20.v20190813.jar gms.war"]
          env:
            - name: EBEAN_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: datahub-secret
                  key: ebean.datasource.username
            - name: EBEAN_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datahub-secret
                  key: ebean.datasource.password
            - name: EBEAN_DATASOURCE_HOST
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: ebean.datasource.host
            - name: EBEAN_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: ebean.datasource.url
            - name: EBEAN_DATASOURCE_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: ebean.datasource.driver
            - name: KAFKA_BOOTSTRAP_SERVER
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: kafka.bootstrap.server
            - name: KAFKA_SCHEMAREGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: kafka.schemaregistry.url
            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: elasticsearch.host
            - name: ELASTICSEARCH_PORT
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: elasticsearch.port
            - name: NEO4J_URI
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: neo4j.uri
            - name: NEO4J_USERNAME
              valueFrom:
                secretKeyRef:
                  name: datahub-secret
                  key: neo4j.username
            - name: NEO4J_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: datahub-secret
                  key: neo4j.password
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-gms-service
  labels:
    app: datahub-gms
spec:
  ports:
    - port: 8080
  selector:
    app: datahub-gms
  type: LoadBalancer     