apiVersion: apps/v1
kind: Deployment
metadata:
  name: datahub-frontend-deployment
  labels:
    app: datahub-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datahub-frontend
  template:
    metadata:
      labels:
        app: datahub-frontend
    spec:
      containers:
        - name: datahub-frontend
          image: linkedin/datahub-frontend:latest
          ports:
          - containerPort: 9001
          env:
            - name: DATAHUB_GMS_HOST
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: datahub.gms.host
            - name: DATAHUB_GMS_PORT
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: datahub.gms.port
            - name: DATAHUB_SECRET
              valueFrom:
                secretKeyRef:
                  name: datahub-secret
                  key: datahub.gms.secret
            - name: DATAHUB_APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: datahub.app.version
            - name: DATAHUB_PLAY_MEM_BUFFER_SIZE
              valueFrom:
                configMapKeyRef:
                  name: datahub-configuration
                  key: datahub.play.mem.buffer.size
---
apiVersion: v1
kind: Service
metadata:
  name: datahub-frontend-service
  labels:
    app: datahub-frontend
spec:
  ports:
    - port: 9001
  selector:
    app: datahub-frontend
  type: LoadBalancer     