# Default values for datahub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

datahub-gms:
  enabled: true
  image:
    repository: linkedin/datahub-gms
    tag: "latest"

datahub-frontend:
  enabled: true
  image:
    repository: linkedin/datahub-frontend
    tag: "latest"

datahub-mae-consumer:
  enabled: true
  image:
    repository: linkedin/datahub-mae-consumer
    tag: "latest"

datahub-mce-consumer:
  enabled: true
  image:
    repository: linkedin/datahub-mce-consumer
    tag: "latest"

global:
  elasticsearch:
    host: "elasticsearch"
    port: "9200"

  kafka:
    bootstrap:
      server: "broker:29092"
    schemaregistry:
      url: "http://schema-registry:8081"

  neo4j:
    host: "neo4j:7474"
    uri: "bolt://neo4j"
    username: "neo4j"
    password:
      secretRef: "neo4j-secrets"
      secretKey: "neo4j-password"

  sql:
    datasource:
      host: "mysql:3306"
      url: "jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true"
      driver: "com.mysql.jdbc.Driver"
      username: "datahub"
      password:
        secretRef: "mysql-secrets"
        secretKey: "mysql-password"

  datahub:
    gms:
      port: "8080"
    appVersion: "1.0"

  hostAliases:
    - ip: "192.168.0.104"
      hostnames:
        - "broker"
        - "mysql"
        - "elasticsearch"
        - "neo4j"