name: Build and publish docker images to docker hub
on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/gms/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-gms
          tags: latest

      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/mce-consumer/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-mce-consumer
          tags: latest
    
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/mae-consumer/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-mae-consumer
          tags: latest
                    
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/frontend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-frontend
          tags: latest
