name: release-tagged docker images
on: 
  release:
    types: [created, edited, published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/gms/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-gms
          tags: ${{ github.ref }}
          
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/mae-consumer/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-mae-consumer
          tags: ${{ github.ref }}
      
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/mce-consumer/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-mce-consumer
          tags: ${{ github.ref }}
      
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/frontend/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-frontend
          tags: ${{ github.ref }}
