name: datahub-mae-consumer docker
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '**.md'
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'linkedin/datahub' }}
    steps:
      - uses: actions/checkout@v2
      - id: tag
        run: |
          TAG=$(echo ${GITHUB_REF} | sed -e 's/refs\/heads\/master/latest/g' | sed -e 's/refs\/tags\///g')
          echo "tag=$TAG"
          echo "::set-output name=tag::$TAG"
      - uses: docker/build-push-action@v1
        with:
          dockerfile: ./docker/mae-consumer/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: linkedin/datahub-mae-consumer
          tags: ${{ steps.tag.outputs.tag }}
      - uses: VaultVulp/gp-docker-action@1.1.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./docker/mae-consumer/Dockerfile
          image-name: datahub-mae-consumer
          image-tag: ${{ steps.tag.outputs.tag }}
