name: documentation

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Whether to use cache'
        required: true
        default: 'true'
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  # release:
  #   types: [published, edited]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.9
      - name: Install Python dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Setup Cache for Gradle
        uses: actions/cache@v2
        if: ${{ github.event.inputs.use_cache != 'false' }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: baseprefix1-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ github.job }}
          restore-keys: |
            baseprefix1-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-
            baseprefix1-${{ runner.os }}-gradle-
      - name: Setup Cache for pip
        uses: actions/cache@v2
        if: ${{ github.event.inputs.use_cache != 'false' }}
        with:
          path: ~/.cache/pip
          key: baseprefix1-${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }}-${{ github.job }}
          restore-keys: |
            baseprefix1-${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }}-
            baseprefix1-${{ runner.os }}-pip-${{ matrix.python-version }}-
            baseprefix1-${{ runner.os }}-pip-
      - name: Build Docs
        run: |
          ./gradlew --info docs-website:build
      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'datahub-project/datahub'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-website/build
          cname: datahubproject.io
