name: documentation

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  # release:
  #   types: [published, edited]

jobs:
  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Docs
        run: |
          ./gradlew --info docs-website:build
      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'linkedin/datahub'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-website/build
          cname: datahubproject.io
