name: metadata model generate
on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Whether to use cache'
        required: true
        default: 'true'
  push:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "**.md"
  release:
    types: [published, edited]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      publish: ${{ steps.publish.outputs.publish }}
    steps:
      - name: Check whether upload to datahub is enabled
        id: publish
        env:
          ENABLE_PUBLISH: ${{ secrets.DataHubToken }}
        run: |
          echo "Enable publish: ${{ env.ENABLE_PUBLISH != '' }}"
          echo "::set-output name=publish::${{ env.ENABLE_PUBLISH != '' }}"
  metadata-ingestion-docgen:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9.9"
      - name: Install dependencies
        run: ./metadata-ingestion/scripts/install_deps.sh
      - name: Setup Cache for Gradle
        uses: actions/cache@v2
        if: ${{ github.event.inputs.use_cache != 'false' }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: baseprefix1-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ github.job }}
          restore-keys: |
            baseprefix1-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-
            baseprefix1-${{ runner.os }}-gradle-
      - name: Setup Cache for pip
        uses: actions/cache@v2
        if: ${{ github.event.inputs.use_cache != 'false' }}
        with:
          path: ~/.cache/pip
          key: baseprefix1-${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }}-${{ github.job }}
          restore-keys: |
            baseprefix1-${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }}-
            baseprefix1-${{ runner.os }}-pip-${{ matrix.python-version }}-
            baseprefix1-${{ runner.os }}-pip-
      - name: Run model generation
        run: ./gradlew :metadata-models:build
      - name: Upload metadata to DataHub
        if: ${{ needs.setup.outputs.publish == 'true' }}
        env:
          DATAHUB_SERVER: ${{ secrets.DataHubServer }}
          DATAHUB_TOKEN: ${{ secrets.DataHubToken }}
        run: ./gradlew :metadata-ingestion:modelDocUpload


